export type ChaosSeverity = 'p0' | 'p1';
export type ChaosRecovery = 'restart' | 'rollback' | 'alert' | 'restore' | 'reprovision';
export interface ChaosScenario { readonly id: string; readonly severity: ChaosSeverity; readonly description: string; readonly injection: readonly string[]; readonly expectedRecovery: ChaosRecovery; readonly expectedDataIntegrity: 'unchanged' | 'restored' | 'not-applicable'; readonly runbook: string; }
export interface ChaosResult { readonly scenario: string; readonly injectedAt: string; readonly detectedAt?: string; readonly recoveredAt?: string; readonly finalHealth: 'healthy' | 'failed' | 'unknown'; readonly dataIntegrity: 'unchanged' | 'restored' | 'corrupt' | 'not-applicable'; readonly alertRaised: boolean; readonly success: boolean; }
export const chaosScenarios: readonly ChaosScenario[] = [
  { id: 'api-kill', severity: 'p0', description: 'Kill production API container', injection: ['docker', 'kill', '${PROD_API_CONTAINER}'], expectedRecovery: 'restart', expectedDataIntegrity: 'unchanged', runbook: 'runbooks/api-crash.md' },
  { id: 'postgres-restart', severity: 'p0', description: 'Restart PostgreSQL dependency', injection: ['docker', 'restart', '${POSTGRES_CONTAINER}'], expectedRecovery: 'restart', expectedDataIntegrity: 'unchanged', runbook: 'runbooks/postgres-recovery.md' },
  { id: 'redis-restart', severity: 'p0', description: 'Restart Redis dependency', injection: ['docker', 'restart', '${REDIS_CONTAINER}'], expectedRecovery: 'restart', expectedDataIntegrity: 'unchanged', runbook: 'runbooks/redis-recovery.md' },
  { id: 'openbao-restart', severity: 'p0', description: 'Restart OpenBao', injection: ['docker', 'restart', '${OPENBAO_CONTAINER}'], expectedRecovery: 'alert', expectedDataIntegrity: 'unchanged', runbook: 'runbooks/openbao-recovery.md' },
  { id: 'vm-reboot', severity: 'p0', description: 'Reboot the real Linux VM', injection: ['vmctl', 'reboot'], expectedRecovery: 'restart', expectedDataIntegrity: 'unchanged', runbook: 'runbooks/vm-reboot.md' },
  { id: 'network-loss', severity: 'p0', description: 'Block outbound network temporarily', injection: ['iptables', '-I', 'OUTPUT', '1', '-m', 'comment', '--comment', 'twilite-chaos-network', '-j', 'DROP'], expectedRecovery: 'restart', expectedDataIntegrity: 'unchanged', runbook: 'runbooks/network-failure.md' },
  { id: 's3-failure', severity: 'p0', description: 'Block backup object storage temporarily', injection: ['env', 'PGBACKREST_S3_FAILURE=1', 'bash', 'infra/backups/pgbackrest/backup.sh'], expectedRecovery: 'alert', expectedDataIntegrity: 'unchanged', runbook: 'runbooks/backup-failure.md' },
  { id: 'disk-pressure', severity: 'p0', description: 'Fill an isolated test filesystem', injection: ['fallocate', '-l', '${CHAOS_DISK_PRESSURE_BYTES}', '${CHAOS_PRESSURE_FILE}'], expectedRecovery: 'alert', expectedDataIntegrity: 'unchanged', runbook: 'runbooks/disk-pressure.md' },
  { id: 'memory-oom', severity: 'p0', description: 'Exercise a bounded memory pressure cgroup', injection: ['systemd-run', '--scope', '-p', 'MemoryMax=${CHAOS_MEMORY_MAX}', 'stress-ng', '--vm', '1', '--vm-bytes', '${CHAOS_MEMORY_BYTES}', '--timeout', '20s'], expectedRecovery: 'alert', expectedDataIntegrity: 'unchanged', runbook: 'runbooks/memory-pressure.md' },
  { id: 'broken-release', severity: 'p0', description: 'Deploy a deliberately unhealthy immutable image', injection: ['bash', 'infra/deploy/deploy.sh'], expectedRecovery: 'rollback', expectedDataIntegrity: 'unchanged', runbook: 'runbooks/deploy-rollback.md' },
  { id: 'migration-failure', severity: 'p0', description: 'Make migration exit non-zero before traffic', injection: ['env', 'MIGRATION_FAILURE=1', 'bash', 'infra/deploy/deploy.sh'], expectedRecovery: 'rollback', expectedDataIntegrity: 'unchanged', runbook: 'runbooks/migration-failure.md' },
  { id: 'unreadable-secret', severity: 'p0', description: 'Remove read access from a disposable secret fixture', injection: ['chmod', '000', '${CHAOS_SECRET_FILE}'], expectedRecovery: 'alert', expectedDataIntegrity: 'unchanged', runbook: 'runbooks/secret-failure.md' },
  { id: 'corrupt-backup', severity: 'p0', description: 'Corrupt an isolated backup copy before restore', injection: ['truncate', '-s', '1', '${CHAOS_BACKUP_COPY}'], expectedRecovery: 'alert', expectedDataIntegrity: 'restored', runbook: 'runbooks/backup-corruption.md' },
  { id: 'failed-restore', severity: 'p0', description: 'Restore into an invalid isolated target', injection: ['env', 'RESTORE_TARGET_DIR=/run/twilite-invalid', 'bash', 'infra/backups/pgbackrest/restore.sh'], expectedRecovery: 'alert', expectedDataIntegrity: 'restored', runbook: 'runbooks/restore-failure.md' },
  { id: 'interrupted-provision', severity: 'p0', description: 'Interrupt provisioning after a major phase', injection: ['kill', '-INT', '${PROVISION_PID}'], expectedRecovery: 'restart', expectedDataIntegrity: 'not-applicable', runbook: 'runbooks/provision-resume.md' },
  { id: 'partial-rerun', severity: 'p0', description: 'Resume from partial provisioning state', injection: ['bash', 'infra/chaos/partial-rerun.sh'], expectedRecovery: 'restart', expectedDataIntegrity: 'not-applicable', runbook: 'runbooks/provision-resume.md' },
  { id: 'vps-loss', severity: 'p0', description: 'Destroy and replace the production-like VM', injection: ['vmctl', 'destroy'], expectedRecovery: 'reprovision', expectedDataIntegrity: 'restored', runbook: 'runbooks/disaster-recovery.md' },
];
export function getChaosScenario(id: string): ChaosScenario { const scenario = chaosScenarios.find((candidate) => candidate.id === id); if (scenario === undefined) throw new Error(`unknown chaos scenario: ${id}`); return scenario; }
export function assertChaosResult(result: ChaosResult, scenario: ChaosScenario): void { if (result.scenario !== scenario.id) throw new Error('chaos result scenario mismatch'); if (!result.success || result.finalHealth !== 'healthy') throw new Error(`chaos scenario failed: ${scenario.id}`); if (result.dataIntegrity !== scenario.expectedDataIntegrity) throw new Error(`chaos data-integrity result mismatch: ${scenario.id}`); }
