/** Executable §1 + D5 memory budget. */
import { permanent } from '../errors.ts';
import { err, ok, type Result } from '../result.ts';
import { integer_, object_, withDefault, type Infer } from './validate.ts';
const mib = (fallback: number) => withDefault(integer_({ min: 16, max: 262144 }), fallback);
export const resourceBudgetCheck = object_({ totalMemoryMiB: withDefault(integer_({ min: 512, max: 1048576 }), 2048), osReserveMiB: mib(512), minReserveDuringJobMiB: mib(256), alwaysOn: object_({ productionApi: mib(384), stagingApi: mib(192), postgres: mib(384), redis: mib(96), openbao: mib(192), reverseProxy: mib(64), monitoringAgent: mib(96) }), transient: object_({ backupJob: mib(128), migrationJob: mib(128) }) });
export type ResourceBudget = Infer<typeof resourceBudgetCheck>;
export interface BudgetSummary { readonly alwaysOnMiB: number; readonly committedMiB: number; readonly largestTransientMiB: number; readonly reserveDuringJobMiB: number; readonly headroomMiB: number; }
export function summariseBudget(budget: ResourceBudget): BudgetSummary { const alwaysOnMiB = Object.values(budget.alwaysOn).reduce((total, value) => total + value, 0); const committedMiB = alwaysOnMiB + budget.osReserveMiB; const largestTransientMiB = Math.max(...Object.values(budget.transient)); return { alwaysOnMiB, committedMiB, largestTransientMiB, reserveDuringJobMiB: budget.osReserveMiB - largestTransientMiB, headroomMiB: budget.totalMemoryMiB - committedMiB }; }
export function assertBudget(budget: ResourceBudget): Result<BudgetSummary> { const summary = summariseBudget(budget); if (summary.headroomMiB < 0) return err(permanent('E_BUDGET_OVERCOMMIT', `container limits + OS reserve (${summary.committedMiB} MiB) exceed host memory (${budget.totalMemoryMiB} MiB)`, { details: { summary } })); if (summary.reserveDuringJobMiB < budget.minReserveDuringJobMiB) return err(permanent('E_BUDGET_RESERVE', `a transient job of ${summary.largestTransientMiB} MiB would leave only ${summary.reserveDuringJobMiB} MiB of OS reserve`, { details: { summary } })); return ok(summary); }
export function formatBudget(budget: ResourceBudget): readonly string[] { const summary = summariseBudget(budget); return [`always-on total     ${String(summary.alwaysOnMiB).padStart(5)} MiB`, ...Object.entries(budget.alwaysOn).map(([name, value]) => `  ${name.padEnd(18)} ${String(value).padStart(5)} MiB`), `os reserve          ${String(budget.osReserveMiB).padStart(5)} MiB`, `committed           ${String(summary.committedMiB).padStart(5)} MiB of ${budget.totalMemoryMiB} MiB`, `transient (max one) ${String(summary.largestTransientMiB).padStart(5)} MiB from the reserve, leaving ${summary.reserveDuringJobMiB} MiB`]; }
