/** Dependency-free validation combinators with path-accurate errors. */
import { permanent, type InfraError } from '../errors.ts';
export interface Issue { readonly path: string; readonly message: string; }
export type CheckResult<T> = { readonly ok: true; readonly value: T } | { readonly ok: false; readonly issues: readonly Issue[] };
export interface Check<T> { (input: unknown, path: string): CheckResult<T>; }
export type Infer<C> = C extends Check<infer T> ? T : never;
const good = <T>(value: T): CheckResult<T> => ({ ok: true, value });
const bad = (path: string, message: string): CheckResult<never> => ({ ok: false, issues: [{ path, message }] });
export function string_(options: { readonly minLength?: number; readonly maxLength?: number; readonly pattern?: RegExp; readonly patternHint?: string } = {}): Check<string> { return (input, path) => { if (typeof input !== 'string') return bad(path, `expected string, got ${typeof input}`); if (options.minLength !== undefined && input.length < options.minLength) return bad(path, `expected at least ${options.minLength} characters`); if (options.maxLength !== undefined && input.length > options.maxLength) return bad(path, `expected at most ${options.maxLength} characters`); if (options.pattern !== undefined && !options.pattern.test(input)) return bad(path, `expected ${options.patternHint ?? options.pattern.source}`); return good(input); }; }
export function integer_(options: { readonly min?: number; readonly max?: number } = {}): Check<number> { return (input, path) => { if (typeof input !== 'number' || !Number.isInteger(input)) return bad(path, `expected integer`); if (options.min !== undefined && input < options.min) return bad(path, `expected >= ${options.min}`); if (options.max !== undefined && input > options.max) return bad(path, `expected <= ${options.max}`); return good(input); }; }
export function boolean_(): Check<boolean> { return (input, path) => typeof input === 'boolean' ? good(input) : bad(path, 'expected boolean'); }
export function oneOf<const T extends readonly string[]>(values: T): Check<T[number]> { return (input, path) => typeof input === 'string' && values.includes(input) ? good(input as T[number]) : bad(path, `expected one of ${values.join(' | ')}`); }
export function array_<T>(item: Check<T>, options: { readonly minItems?: number } = {}): Check<readonly T[]> { return (input, path) => { if (!Array.isArray(input)) return bad(path, 'expected array'); if (options.minItems !== undefined && input.length < options.minItems) return bad(path, `expected at least ${options.minItems} item(s)`); const issues: Issue[] = []; const values: T[] = []; input.forEach((element, index) => { const result = item(element, `${path}[${index}]`); if (result.ok) values.push(result.value); else issues.push(...result.issues); }); return issues.length > 0 ? { ok: false, issues } : good(values); }; }
type Shape = Record<string, Check<unknown>>; type ShapeOutput<S extends Shape> = { readonly [K in keyof S]: Infer<S[K]> };
export function object_<S extends Shape>(shape: S): Check<ShapeOutput<S>> { return (input, path) => { if (input !== undefined && (input === null || typeof input !== 'object' || Array.isArray(input))) return bad(path, 'expected object'); const source = (input ?? {}) as Record<string, unknown>; const issues: Issue[] = []; const output: Record<string, unknown> = {}; for (const [key, check] of Object.entries(shape)) { const result = check(source[key], path === '' ? key : `${path}.${key}`); if (result.ok) output[key] = result.value; else issues.push(...result.issues); } for (const key of Object.keys(source)) if (!(key in shape)) issues.push({ path: path === '' ? key : `${path}.${key}`, message: 'unknown configuration key' }); return issues.length > 0 ? { ok: false, issues } : good(output as ShapeOutput<S>); }; }
export function withDefault<T>(check: Check<T>, fallback: T): Check<T> { return (input, path) => input === undefined ? good(fallback) : check(input, path); }
export function maybe<T>(check: Check<T>): Check<T | undefined> { return (input, path) => input === undefined ? good(undefined) : check(input, path); }
export function refine<T>(check: Check<T>, rule: (value: T) => string | undefined): Check<T> { return (input, path) => { const result = check(input, path); if (!result.ok) return result; const message = rule(result.value); return message === undefined ? result : bad(path === '' ? '<root>' : path, message); }; }
export const hostname_ = (): Check<string> => string_({ minLength: 1, maxLength: 253, pattern: /^[A-Za-z0-9]([A-Za-z0-9.-]*[A-Za-z0-9])?$/, patternHint: 'a hostname, IPv4 address or DNS name' });
export const port_ = (): Check<number> => integer_({ min: 1, max: 65535 });
export const unixUser_ = (): Check<string> => string_({ minLength: 1, maxLength: 32, pattern: /^[a-z_][a-z0-9_-]*$/, patternHint: 'a lowercase POSIX user name' });
export function toError(issues: readonly Issue[], source: string): InfraError { return permanent('E_CONFIG_INVALID', `invalid configuration (${source}):\n${issues.map((issue) => `  - ${issue.path}: ${issue.message}`).join('\n')}`, { details: { source, issues } }); }
