import { createHash } from 'node:crypto';
import { createReadStream, createWriteStream, existsSync, mkdirSync, unlinkSync } from 'node:fs';
import { get } from 'node:https';
import { dirname } from 'node:path';
export const UBUNTU_IMAGE_URL = 'https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-amd64.img';
export const UBUNTU_IMAGE_SHA256 = '6e40c07ae715f744f84af0bec76415cc1987dd115b4b8de437818561f01a3733';
export async function ensureUbuntuImage(path: string): Promise<void> { mkdirSync(dirname(path), { recursive: true }); if (!existsSync(path)) await download(UBUNTU_IMAGE_URL, path); const actual = await sha256(path); if (actual !== UBUNTU_IMAGE_SHA256) { try { unlinkSync(path); } catch { /* preserve verification failure */ } throw new Error(`Ubuntu image checksum mismatch: expected ${UBUNTU_IMAGE_SHA256}, got ${actual}`); } }
function download(url: string, destination: string): Promise<void> { return new Promise((resolve, reject) => { const request = get(url, (response) => { if (response.statusCode !== 200) { response.resume(); reject(new Error(`image download returned HTTP ${response.statusCode ?? 'unknown'}`)); return; } const file = createWriteStream(destination, { flags: 'wx' }); response.pipe(file); file.on('finish', () => file.close((error) => error === undefined || error === null ? resolve() : reject(error))); file.on('error', reject); }); request.setTimeout(120000, () => request.destroy(new Error('image download timed out'))); request.on('error', reject); }); }
function sha256(path: string): Promise<string> { return new Promise((resolve, reject) => { const hash = createHash('sha256'); const stream = createReadStream(path); stream.on('data', (chunk: Buffer) => hash.update(chunk)); stream.on('error', reject); stream.on('end', () => resolve(hash.digest('hex'))); }); }
