/** Pure resumable provisioning state machine. */
import { permanent } from '../errors.ts';
import { err, ok, type Result } from '../result.ts';
import { PHASES, STATE_SCHEMA_VERSION, TERMINAL_STEP_STATUSES, phaseIndex, type Phase, type RunState, type RunStatus, type StepRecord, type StepStatus } from './types.ts';
export interface CreateRunStateInput { readonly runId: string; readonly configFingerprint: string; readonly host: string; readonly label: string; readonly cliVersion: string; readonly dryRun: boolean; readonly now: string; }
export function createRunState(input: CreateRunStateInput): RunState { return { schemaVersion: STATE_SCHEMA_VERSION, runId: input.runId, createdAt: input.now, updatedAt: input.now, configFingerprint: input.configFingerprint, target: { host: input.host, label: input.label }, cliVersion: input.cliVersion, phase: PHASES[0], status: 'pending', dryRun: input.dryRun, steps: {}, completedPhases: [] }; }
const RUN_TRANSITIONS: Readonly<Record<RunStatus, readonly RunStatus[]>> = { pending: ['running','cancelled','failed'], running: ['running','completed','failed','cancelled'], completed: ['running'], failed: ['running','cancelled'], cancelled: ['running'] };
export function canTransition(from: RunStatus, to: RunStatus): boolean { return (RUN_TRANSITIONS[from] ?? []).includes(to); }
export function withRunStatus(state: RunState, status: RunStatus, now: string): Result<RunState> { if (!canTransition(state.status, status)) return err(permanent('E_STATE_TRANSITION', `illegal run transition ${state.status} -> ${status}`, { details: { from: state.status, to: status } })); return ok({ ...state, status, updatedAt: now }); }
export function withPhase(state: RunState, phase: Phase, now: string): Result<RunState> { const current = phaseIndex(state.phase); const next = phaseIndex(phase); if (next < current) return err(permanent('E_PHASE_REGRESSION', `cannot move backwards from ${state.phase} to ${phase}`)); if (next > current + 1) return err(permanent('E_PHASE_SKIPPED', `cannot skip from ${state.phase} to ${phase}`)); if (next === current) return ok(state); const completedPhases = state.completedPhases.includes(state.phase) ? state.completedPhases : [...state.completedPhases, state.phase]; return ok({ ...state, phase, completedPhases, updatedAt: now }); }
export function upsertStep(state: RunState, record: StepRecord, now: string): RunState { return { ...state, updatedAt: now, steps: { ...state.steps, [record.stepId]: record } }; }
export function stepStatus(state: RunState, stepId: string): StepStatus { return state.steps[stepId]?.status ?? 'pending'; }
export function isStepComplete(state: RunState, stepId: string): boolean { return TERMINAL_STEP_STATUSES.includes(stepStatus(state, stepId)); }
export function pendingSteps(state: RunState, stepIds: readonly string[]): readonly string[] { return stepIds.filter((stepId) => !isStepComplete(state, stepId)); }
export type ResumeDecision = { readonly kind: 'start' } | { readonly kind: 'resume'; readonly fromPhase: Phase; readonly completedSteps: number } | { readonly kind: 'reinstall' } | { readonly kind: 'nothing-to-do' } | { readonly kind: 'incompatible'; readonly reason: string };
export function decideResume(input: { readonly state: RunState | undefined; readonly configFingerprint: string; readonly requested: 'auto' | 'resume' | 'reinstall' }): ResumeDecision { const { state } = input; if (input.requested === 'reinstall') return { kind: 'reinstall' }; if (state === undefined) return { kind: 'start' }; if (state.schemaVersion !== STATE_SCHEMA_VERSION) return { kind: 'incompatible', reason: `state schema ${state.schemaVersion} != supported ${STATE_SCHEMA_VERSION}` }; if (state.configFingerprint !== input.configFingerprint) return { kind: 'incompatible', reason: 'configuration changed since the previous run' }; if (state.status === 'completed') return { kind: 'nothing-to-do' }; return { kind: 'resume', fromPhase: state.phase, completedSteps: Object.values(state.steps).filter((step) => TERMINAL_STEP_STATUSES.includes(step.status)).length }; }
export function summarise(state: RunState): { readonly total: number; readonly success: number; readonly skipped: number; readonly failed: number; readonly rolledBack: number } { const values = Object.values(state.steps); const count = (status: StepStatus): number => values.filter((step) => step.status === status).length; return { total: values.length, success: count('success'), skipped: count('skipped'), failed: count('failed'), rolledBack: count('rolled_back') }; }
