/** Bounded exponential retry with injectable clock and full jitter. */
import { cancelled, isTransient, toInfraError, type InfraError } from './errors.ts';
import { systemClock, type Clock } from './util/time.ts';
export interface RetryPolicy { readonly maxAttempts: number; readonly initialDelayMs: number; readonly maxDelayMs: number; readonly backoffFactor: number; readonly jitter: 'full' | 'none'; }
export const defaultRetryPolicy: RetryPolicy = { maxAttempts: 4, initialDelayMs: 1000, maxDelayMs: 15000, backoffFactor: 2, jitter: 'full' };
export interface RetryAttemptInfo { readonly attempt: number; readonly maxAttempts: number; readonly delayMs: number; readonly error: InfraError; }
export interface RetryOptions { readonly policy?: RetryPolicy; readonly clock?: Clock; readonly rng?: () => number; readonly signal?: AbortSignal; readonly onRetry?: (info: RetryAttemptInfo) => void; readonly isRetryable?: (error: InfraError) => boolean; }
export function computeDelay(policy: RetryPolicy, attempt: number, random: number): number { const exponential = policy.initialDelayMs * policy.backoffFactor ** (attempt - 1); const capped = Math.min(exponential, policy.maxDelayMs); return policy.jitter === 'full' ? Math.round(capped * random) : Math.round(capped); }
export interface RetryOutcome<T> { readonly value: T; readonly attempts: number; }
export async function withRetry<T>(operation: (attempt: number) => Promise<T>, options: RetryOptions = {}): Promise<RetryOutcome<T>> { const policy = options.policy ?? defaultRetryPolicy; if (policy.maxAttempts < 1) throw new Error('retry policy requires maxAttempts >= 1'); const clock = options.clock ?? systemClock; const rng = options.rng ?? Math.random; const retryable = options.isRetryable ?? ((error: InfraError) => isTransient(error)); let attempt = 0; for (;;) { attempt += 1; if (options.signal?.aborted === true) throw cancelled(); try { return { value: await operation(attempt), attempts: attempt }; } catch (thrown) { const error = toInfraError(thrown); if (error.kind === 'cancelled' || options.signal?.aborted === true) throw error; if (attempt >= policy.maxAttempts || !retryable(error)) throw error; const delayMs = computeDelay(policy, attempt, rng()); options.onRetry?.({ attempt, maxAttempts: policy.maxAttempts, delayMs, error }); await clock.sleep(delayMs, options.signal); } } }
export async function withTimeout<T>(operation: (signal: AbortSignal) => Promise<T>, timeoutMs: number, label: string, parentSignal?: AbortSignal): Promise<T> { const controller = new AbortController(); const onParentAbort = (): void => controller.abort(parentSignal?.reason); parentSignal?.addEventListener('abort', onParentAbort, { once: true }); const timer = setTimeout(() => controller.abort(new Error(`timeout after ${timeoutMs}ms`)), timeoutMs); try { return await operation(controller.signal); } catch (thrown) { if (controller.signal.aborted && parentSignal?.aborted !== true) throw toInfraError(Object.assign(new Error(`${label} timed out after ${timeoutMs}ms`), { code: 'ETIMEDOUT' }), 'E_TIMEOUT'); throw toInfraError(thrown); } finally { clearTimeout(timer); parentSignal?.removeEventListener('abort', onParentAbort); } }
