export type BackupArtifactKind = 'base' | 'wal' | 'logical' | 'raft-snapshot';
export type RecoveryValidation = 'download' | 'decrypt' | 'restore' | 'integrity' | 'smoke';
export interface BackupPolicy { readonly rpoMinutes: number; readonly restoreRtoMinutes: number; readonly archiveTimeoutSeconds: number; readonly freshnessAlertSeconds: number; readonly dailyDays: number; readonly weeklyWeeks: number; readonly monthlyMonths: number; readonly stagingExpendable: boolean; }
export interface BackupCommand { readonly name: string; readonly args: readonly string[]; readonly env: Readonly<Record<string, string>>; }
export interface RestoreReport { readonly artifact: string; readonly targetTimestamp?: string; readonly validations: readonly RecoveryValidation[]; readonly measuredRpoSeconds?: number; readonly measuredRtoSeconds?: number; readonly stagingReseedRequired: boolean; readonly success: boolean; }
export const defaultBackupPolicy: BackupPolicy = { rpoMinutes: 5, restoreRtoMinutes: 60, archiveTimeoutSeconds: 60, freshnessAlertSeconds: 180, dailyDays: 7, weeklyWeeks: 4, monthlyMonths: 3, stagingExpendable: true };
export function buildPgBackrestBackupCommand(config: { readonly stanza: string; readonly configPath: string; readonly repoCipherPassFile: string }): BackupCommand { return { name: 'pgbackrest-backup', args: ['pgbackrest', '--config', config.configPath, '--stanza', config.stanza, 'backup', '--type=full', '--repo=1'], env: { PGBACKREST_REPO1_CIPHER_PASS_FILE: config.repoCipherPassFile } }; }
export function buildPgBackrestRestoreCommand(config: { readonly stanza: string; readonly configPath: string; readonly targetTimestamp?: string }): BackupCommand { const args = ['pgbackrest', '--config', config.configPath, '--stanza', config.stanza, 'restore', '--delta', '--type=time']; if (config.targetTimestamp !== undefined) args.push(`--target=${config.targetTimestamp}`); return { name: 'pgbackrest-restore', args, env: {} }; }
export function assertRecoveryReport(report: RestoreReport, policy: BackupPolicy = defaultBackupPolicy): void { const required: readonly RecoveryValidation[] = ['download', 'decrypt', 'restore', 'integrity', 'smoke']; for (const validation of required) if (!report.validations.includes(validation)) throw new Error(`restore validation missing: ${validation}`); if (!report.success) throw new Error('restore report is unsuccessful'); if (report.measuredRpoSeconds !== undefined && report.measuredRpoSeconds > policy.rpoMinutes * 60) throw new Error('measured RPO exceeds policy'); if (report.measuredRtoSeconds !== undefined && report.measuredRtoSeconds > policy.restoreRtoMinutes * 60) throw new Error('measured RTO exceeds policy'); if (!report.stagingReseedRequired && policy.stagingExpendable) throw new Error('cluster-wide PITR must require staging re-seed'); }
export function renderRestoreSummary(report: RestoreReport): string { return JSON.stringify({ ...report, secrets: undefined }, null, 2); }
